### PR TITLE
Update to v2.0.0

### PR DESCRIPTION
**Pull request by hobu**
LAStools has begun version tagging their releases at https://github.com/LAStools/LAStools

This PR updates a number of things:

* adds @hobu as a maintainer
* adds osx-arm64 and linux arm64 build configs
* points to LAStools release

### CODE REVIEW

**Comment by gillins** [comment]
Thanks @hobu - this is great news. I was worried they were never going to do this...

BTW do you know what the status of `pulsewaves` is (https://github.com/conda-forge/pulsewaves-feedstock, https://github.com/PulseWaves/PulseWaves) - maybe this can be archived as there seems to be no recent activity upstream?

**Comment by hobu** [comment]
AFAIK, there hadn't been any PulseWaves activity for years. With Martin's death, I doubt anyone is going to pick it up.

**Comment by gillins** [comment]
@hobu I've reverted back to what the old recipe did which was to create a shared lib in case there are downstream projects that may need it (not sure if there are, but just in case). It was a bit of a mess but I got it going in the end. Are you happy with this approach?

**Comment by hobu** [comment]
Works for me.

**Pull request merged**
